---
resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: prometheus-boshrelease
  type: git
  source:
    uri: https://github.com/bosh-prometheus/prometheus-boshrelease
    branch: master
    tag_filer: v25.0.0

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

- name: version
  type: concourse-version-resource

jobs:
- name: populate-credhub
  public: true
  serial: true
  plan:
  - get: version
  - get: bbl-state
  - task: populate-credhub
    file: cf-pipelines/prometheus/tasks/populate-credhub/task.yml
  - put: version

- name: deploy
  public: true
  serial: true
  plan:
  - get: version
    passed: [populate-credhub]
    trigger: true
  - get: prometheus-boshrelease
  - get: bbl-state
  - task: deploy
    file: cf-pipelines/prometheus/tasks/bosh-deploy/task.yml
    params:
      BBL_ENV: ((bbl_env))
      OPS_FILES: ((ops_files))
     