resources:
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master
    tag_filter: ((cf_version))

- name: prometheus-boshrelease
  type: git
  source:
    uri: https://github.com/bosh-prometheus/prometheus-boshrelease
    branch: master
    tag_filer: ((prometheus_version))

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/alexw19/cf-deployment-concourse-tasks.git
    branch: master

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

groups:
- name: create
  jobs:
  - deploy-cf
  - smoke-tests
- name: destroy
  jobs:
  - delete-cf

jobs:
- name: deploy-cf
  plan:
  - get: cf-deployment
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
  - get: prometheus-boshrelease
  - task: collect-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    input_mapping:
      base-ops-files: cf-deployment
      new-ops-files: prometheus-boshrelease
    params:
      BASE_OPS_FILE_DIR: operations
      NEW_OPS_FILES: ((prometheus_ops_files))
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      ops-files: collected-ops-files
      vars-files: bbl-state
    params:
      BBL_CONFIG_DIR: ((bbl_env))/config
      BBL_STATE_DIR: ((bbl_env))/state
      INFRASTRUCTURE: ((BBL_IAAS))
      SYSTEM_DOMAIN: ((cf_domain))
      OPS_FILES: ((collected_ops_files))
      VARS_FILES: ((bbl_env))/vars/cf/bosh-vars.yml

- name: smoke-tests
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - deploy-cf
    trigger: true
  - task: smoke-tests
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    params:
      BBL_STATE_DIR: ((bbl_env))/state
      ERRAND_NAME: smoke-tests

- name: delete-cf
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - deploy-cf
  - task: delete-cf
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      BBL_STATE_DIR: ((bbl_env))/state
