---
resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

resources:
- name: cf-mysql-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-mysql-deployment
    branch: develop

- name: cf-pipelines
  type: git
  source:
    uri: https://github.com/axelaris/cf-pipelines.git
    branch: master

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

- name: version
  type: concourse-version-resource

jobs:
- name: populate-credhub
  public: true
  serial: true
  plan:
  - get: version
  - get: bbl-state
  - task: populate-credhub
    file: cf-pipelines/mysql/tasks/populate-credhub/task.yml
    params:
      BBL_ENV: ((bbl_env))
  - put: version

- name: deploy-mysql
  public: true
  serial: true
  plan:
  - get: version
    passed: [populate-credhub]
    trigger: true
  - get: cf-mysql-deployment
  - get: cf-pipelines
  - get: bbl-state
  - task: deploy-mysql
    file: cf-pipelines/mysql/tasks/bosh-deploy/task.yml
    params:
      OPS_FILES: ((ops_files))
      BBL_ENV: ((bbl_env))
  - put: version
     
- name: broker-registrar
  plan:
  - get: version
    passed: [deploy-mysql]
    trigger: true
  - get: bbl-state
  - get: cf-pipelines
  - task: run-errand
    file: cf-pipelines/mysql/tasks/run-errand/task.yml
    params:
      BBL_ENV: ((bbl_env))
      ERRAND: broker-registrar
  - put: version

- name: run-smoke-tests
  public: true
  serial: true
  plan:
  - get: version
    passed: [broker-registrar]
    trigger: true
  - get: bbl-state
  - get: cf-pipelines
  - task: run-errand
    file: cf-pipelines/mysql/tasks/run-errand/task.yml
    params:
      BBL_ENV: ((bbl_env))
      ERRAND: smoke-tests

- name: broker-deregistrar
  public: true
  serial: true
  plan:
  - get: version
    passed: [broker-registrar]
  - get: bbl-state
  - task: run-errand
    file: cf-pipelines/mysql/tasks/run-errand/task.yml
    params:
      BBL_ENV: ((bbl_env))
      ERRAND: deregister-and-purge-instances
