resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    branch: master
    tag_filter: v9.0.0

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

groups:
- name: create
  jobs:
  - bootstrap-env
- name: destroy
  jobs:
  - wipe-env

jobs:
- name: bootstrap-env
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-config: bbl-state
      updated-bbl-state: bbl-state
    params:
      BBL_IAAS: ((BBL_IAAS))
      BBL_CONFIG_DIR: ((BBL_ENV_NAME))/config
      BBL_STATE_DIR: ((BBL_ENV_NAME))/state
      BBL_ENV_NAME: ((BBL_ENV_NAME))
      BBL_AWS_ACCESS_KEY_ID: ((BBL_AWS_ACCESS_KEY_ID))
      BBL_AWS_SECRET_ACCESS_KEY: ((BBL_AWS_SECRET_ACCESS_KEY))
      BBL_AWS_REGION: ((BBL_AWS_REGION))
      BBL_LB_CERT: ((BBL_LB_CERT))
      BBL_LB_CERT_CHAIN: ((BBL_LB_CERT_CHAIN))
      BBL_LB_KEY: ((BBL_LB_KEY))
      LB_DOMAIN: ((LB_DOMAIN))
      GIT_COMMIT_EMAIL: ((git_commit_email))
      DEBUG_MODE: true
  ensure:
    put: bbl-state
    params:
      repository: updated-bbl-state
      rebase: true

- name: wipe-env
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - bootstrap-env
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      updated-bbl-state: bbl-state
    params:
      BBL_STATE_DIR: ((BBL_ENV_NAME))/state
      BBL_IAAS: ((BBL_IAAS))
      BBL_CONFIG_DIR: ((BBL_ENV_NAME))/config
      BBL_STATE_DIR: ((BBL_ENV_NAME))/state
      BBL_ENV_NAME: ((BBL_ENV_NAME))
      BBL_AWS_ACCESS_KEY_ID: ((BBL_AWS_ACCESS_KEY_ID))
      BBL_AWS_SECRET_ACCESS_KEY: ((BBL_AWS_SECRET_ACCESS_KEY))
      BBL_AWS_REGION: ((BBL_AWS_REGION))
      GIT_COMMIT_EMAIL: ((git_commit_email))
  ensure:
    put: bbl-state
    params:
      repository: updated-bbl-state
      rebase: true

