resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

resources:

- name: version
  type: concourse-version-resource

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    branch: master
    tag_filter: v9.0.0

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

- name: cf-pipelines
  type: git
  source:
    uri: https://github.com/axelaris/cf-pipelines.git
    branch: master

groups:
- name: create
  jobs:
  - populate-credhub
  - bootstrap-env
- name: destroy
  jobs:
  - wipe-env

jobs:
- name: populate-credhub
  plan:
  - get: version
  - get: bbl-state
  - get: cf-pipelines
  - task: populate-credhub
    file: cf-pipelines/bbl/tasks/populate-credhub/task.yml
    params:
      BBL_ENV: ((BBL_ENV_NAME))
  - put: version

- name: bootstrap-env
  plan:
  - get: version
    passed: 
    - populate-credhub
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-config: bbl-state
      updated-bbl-state: bbl-state
    params:
      BBL_IAAS: ((BBL_IAAS))
      BBL_CONFIG_DIR: ((BBL_ENV_NAME))/config
      BBL_STATE_DIR: ((BBL_ENV_NAME))/state
      BBL_ENV_NAME: ((BBL_ENV_NAME))
      BBL_AWS_ACCESS_KEY_ID: ((BBL_AWS_ACCESS_KEY_ID))
      BBL_AWS_SECRET_ACCESS_KEY: ((BBL_AWS_SECRET_ACCESS_KEY))
      BBL_AWS_REGION: ((BBL_AWS_REGION))
      BBL_LB_CERT: ((tls.certificate))
      BBL_LB_CERT_CHAIN: ((tls.ca))
      BBL_LB_KEY: ((tls.private_key))
      LB_DOMAIN: ((LB_DOMAIN))
      # Next 4 vars due to BBL bug:
      TF_VAR_ssl_certificate: ((tls.certificate))
      TF_VAR_ssl_certificate_chain: ((tls.ca))
      TF_VAR_ssl_certificate_private_key: ((tls.private_key))
      TF_VAR_system_domain: ((LB_DOMAIN))
      GIT_COMMIT_EMAIL: ((git_commit_email))
      DEBUG_MODE: true
  ensure:
    put: bbl-state
    params:
      repository: updated-bbl-state
      rebase: true

- name: wipe-env
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - bootstrap-env
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      updated-bbl-state: bbl-state
    params:
      BBL_STATE_DIR: ((BBL_ENV_NAME))/state
      BBL_IAAS: ((BBL_IAAS))
      BBL_CONFIG_DIR: ((BBL_ENV_NAME))/config
      BBL_STATE_DIR: ((BBL_ENV_NAME))/state
      BBL_ENV_NAME: ((BBL_ENV_NAME))
      BBL_AWS_ACCESS_KEY_ID: ((BBL_AWS_ACCESS_KEY_ID))
      BBL_AWS_SECRET_ACCESS_KEY: ((BBL_AWS_SECRET_ACCESS_KEY))
      BBL_AWS_REGION: ((BBL_AWS_REGION))
      GIT_COMMIT_EMAIL: ((git_commit_email))
  ensure:
    put: bbl-state
    params:
      repository: updated-bbl-state
      rebase: true

