resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource

resources:
- name: version
  type: concourse-version-resource

- name: logsearch-boshrelease
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/logsearch-boshrelease.git
    branch: develop
    tag_filter: ((logsearch_version))

- name: cf-pipelines
  type: git
  source:
    uri: https://github.com/axelaris/cf-pipelines.git
    branch: master

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

groups:
- name: create
  jobs:
  - populate-credhub
  - deploy-logsearch
  - smoke-tests
  - create-uaa-client
  - upload-kibana-objects
- name: destroy
  jobs:
  - delete-logsearch

jobs:
- name: populate-credhub
  plan:
  - get: version
  - get: bbl-state
  - get: cf-pipelines
  - task: populate-credhub
    file: cf-pipelines/logsearch/tasks/populate-credhub/task.yml
    params:
      BBL_ENV: ((bbl_env))
      SYSTEM_DOMAIN: ((system_domain))
  - put: version

- name: deploy-logsearch
  plan:
  - get: version
    passed:
    - populate-credhub
    trigger: true
  - get: logsearch-boshrelease
  - get: cf-pipelines
  - get: bbl-state
  - task: deploy-logsearch
    file: cf-pipelines/logsearch/tasks/deploy/task.yml
    params:
      BBL_ENV: ((bbl_env))
      OPS_FILES: ((ops_files))
      
- name: smoke-tests
  plan:
  - get: cf-pipelines
  - get: bbl-state
  - get: version
    passed:
    - deploy-logsearch
    trigger: true
  - task: smoke-tests
    file: cf-pipelines/logsearch/tasks/run-errand/task.yml
    params:
      BBL_ENV: ((bbl_env))
      ERRAND_NAME: smoke-tests

- name: create-uaa-client
  plan:
  - get: cf-pipelines
  - get: bbl-state
  - get: version
    passed:
    - smoke-tests
    trigger: false
  - task: create-uaa-client
    file: cf-pipelines/logsearch/tasks/run-errand/task.yml
    params:
      BBL_ENV: ((bbl_env))
      ERRAND_NAME: create-uaa-client

- name: upload-kibana-objects
  plan:
  - get: cf-pipelines
  - get: bbl-state
  - get: version
    passed:
    - create-uaa-client
    trigger: false
  - task: upload-kibana-objects
    file: cf-pipelines/logsearch/tasks/run-errand/task.yml
    params:
      BBL_ENV: ((bbl_env))
      ERRAND_NAME: upload-kibana-objects

- name: delete-logsearch
  plan:
  - get: cf-pipelines
  - get: bbl-state
  - task: delete-logsearch
    file: cf-pipelines/logsearch/tasks/delete/task.yml
    params:
      BBL_ENV: ((bbl_env))
