resources:
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: master
    tag_filter: ((cf_version))

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/alexw19/cf-deployment-concourse-tasks.git
    branch: master
    #tag_filter: v7.*

- name: bbl-state
  type: git
  source:
    uri: ((bbl_state_repo))
    branch: master
    private_key: ((git_private_key))

jobs:
- name: bootstrap-env
  plan:
  - get: cf-deployment
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      bbl-config: bbl-state
      updated-bbl-state: bbl-state
    params:
      LB_DOMAIN: ((cf_domain))
      SKIP_LB_CREATION: true
      BBL_IAAS: vsphere
      BBL_CONFIG_DIR: bbl-config
      BBL_VSPHERE_VCENTER_USER: ((VSPHERE_VCENTER_USER))
      BBL_VSPHERE_VCENTER_PASSWORD: ((VSPHERE_VCENTER_PASSWORD))
      BBL_VSPHERE_VCENTER_IP: ((VSPHERE_VCENTER_IP))
      BBL_VSPHERE_VCENTER_DC: ((VSPHERE_VCENTER_DC))
      BBL_VSPHERE_VCENTER_CLUSTER: ((VSPHERE_VCENTER_CLUSTER))
      BBL_VSPHERE_VCENTER_RP: ((VSPHERE_VCENTER_RP))
      BBL_VSPHERE_NETWORK: ((VSPHERE_NETWORK))
      BBL_VSPHERE_VCENTER_DS: ((VSPHERE_VCENTER_DS))
      BBL_VSPHERE_SUBNET_CIDR: ((VSPHERE_SUBNET_CIDR))
      BBL_VSPHERE_VCENTER_DISKS: ((VSPHERE_VCENTER_DISKS))
      BBL_VSPHERE_VCENTER_TEMPLATES: ((VSPHERE_VCENTER_TEMPLATES))
      BBL_VSPHERE_VCENTER_VMS: ((VSPHERE_VCENTER_VMS))
      GIT_COMMIT_EMAIL: ((git_commit_email))
      DEBUG_MODE: true
  ensure:
    put: bbl-state
    params:
      repository: updated-bbl-state
      rebase: true

- name: upload-stemcells
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - bootstrap-env
    trigger: true
  - get: cf-deployment
    trigger: true
  - task: upload-stemcells
    file: cf-deployment-concourse-tasks/bosh-upload-stemcells/task.yml
    params:
      INFRASTRUCTURE: vsphere

- name: deploy-cf
  plan:
  - get: cf-deployment
    passed:
    - upload-stemcells
    trigger: true
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - upload-stemcells
    trigger: true
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      ops-files: cf-deployment
      vars-files: bbl-state
    params:
      SYSTEM_DOMAIN: ((cf_domain))
      OPS_FILES: "operations/scale-to-one-az.yml"
      #OPS_FILES: "operations/aws.yml operations/scale-to-one-az.yml operations/scale-cells.yml operations/addons/enable-component-syslog.yml operations/addons/component-syslog-custom-ca.yml"
      #VARS_FILES: "cf-vars.yml"

- name: smoke-tests
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - deploy-cf
    trigger: true
  - task: smoke-tests
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    params:
      ERRAND_NAME: smoke-tests

- name: delete-cf
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - deploy-cf
  - task: delete-cf
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml

- name: wipe-env
  plan:
  - get: cf-deployment-concourse-tasks
  - get: bbl-state
    passed:
    - bootstrap-env
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      updated-bbl-state: bbl-state
    params:
      BBL_VSPHERE_VCENTER_USER: ((VSPHERE_VCENTER_USER))
      BBL_VSPHERE_VCENTER_PASSWORD: ((VSPHERE_VCENTER_PASSWORD))
      BBL_VSPHERE_VCENTER_IP: ((VSPHERE_VCENTER_IP))
      BBL_VSPHERE_VCENTER_DC: ((VSPHERE_VCENTER_DC))
      BBL_VSPHERE_VCENTER_CLUSTER: ((VSPHERE_VCENTER_CLUSTER))
      BBL_VSPHERE_VCENTER_RP: ((VSPHERE_VCENTER_RP))
      BBL_VSPHERE_NETWORK: ((VSPHERE_NETWORK))
      BBL_VSPHERE_VCENTER_DS: ((VSPHERE_VCENTER_DS))
      BBL_VSPHERE_SUBNET_CIDR: ((VSPHERE_SUBNET_CIDR))
      BBL_VSPHERE_VCENTER_DISKS: ((VSPHERE_VCENTER_DISKS))
      BBL_VSPHERE_VCENTER_TEMPLATES: ((VSPHERE_VCENTER_TEMPLATES))
      BBL_VSPHERE_VCENTER_VMS: ((VSPHERE_VCENTER_VMS))
      GIT_COMMIT_EMAIL: ((git_commit_email))
  ensure:
    put: bbl-state
    params:
      repository: updated-bbl-state
      rebase: true
